### ISSUE TITLE
Included example webapp confusing

### ISSUE THREAD

**Issue by jzlcdh** [ripple/gatewayd#372]
Compared to the StroopWafel example webapp the example gatewayd-admin webapp included with gatewayd is, in my opinion, confusing. For example it is not clear what "Gateway transactions" are and why we need a data entry screen for "Ripple Transactions" when I thought gatewayd would deal with the ripple transactions for us.

Could either the example webapp be made more similar to the Stroopwafel example webapp or (if it is actually necessary to have 2 examples) could the Stroopwafel example webapp itself be included and updated for e.g. KYC?

**Comment by jzlcdh** [comment]
Thanks.

**Comment by wksantiago** [comment]
Perfect thanks @hserang
