### ISSUE TITLE
Logging options out of date in install instructions and default lib/data/database.json

### ISSUE THREAD

**Issue by jzlcdh** [ripple/gatewayd#441]
From the deprecation warning below it seems the  logging options are not quite right in lib/data/database.json default (and also should be either updated in the install instructions or removed).

----------------------------------
gateuser@c4012:~/gatewayd$ bin/gateway start
DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log
Starting gateway processes and running `pm2 list`...
┌─────────────┬────┬──────┬──────┬────────┬───────────┬────────┬─────────────┬──────────┐
│ App name    │ id │ mode │ PID  │ status │ restarted │ uptime │      memory │ watching │
├─────────────┼────┼──────┼──────┼────────┼───────────┼────────┼─────────────┼──────────┤
│ withdrawals │ 0  │ fork │ 3065 │ online │         0 │ 2s     │ 78.008 MB   │ disabled │
└─────────────┴────┴──────┴──────┴────────┴───────────┴────────┴─────────────┴──────────┘

 Use `pm2 info <id|name>` to get more details about an app

gateuser@c4012:~/gatewayd$
------------------------------

And as a minor point the instructions could include
 sudo apt-get install nano
and edit your password(s) into lib/data/database.json

**Comment by cdmcnamara** [comment]
This has been resolved as all logging now defaults to false.
