### ISSUE TITLE
Webapp example getting connected

### ISSUE THREAD

**Issue by wksantiago** [ripple/gatewayd#505]
Going to https://localhost:5000 
I get a login page but the following:

username: admin@example.com
password: api key

Does not get me in.  Where can I look to see which password and username I should be using.

Thanks,

**Comment by nimmaj** [comment]
I had this issue too.  In my case the chrome javascript console showed that the /v1/users/login was not found.  I then set USER_AUTH to true in config/config.json as this, in app.js, used the user_router.js which had all the users/login defined in it.  

Not entirely sure this is the right thing to do, or why you can turn this off independently of the BASIC_AUTH, but it gets me over the next hurdle ;-)

**Comment by wksantiago** [comment]
nimmaj,

I changed USER_AUTH to true and /v1/users/login was not found did not appear but I could not find where or what to change in app.js, or user_router.js. Can you elaborate?

Thanks,

**Comment by wksantiago** [comment]
Disregard I was able to restart the server and then it worked.
