### ISSUE TITLE
Logging in as admin on the gateway web interface. What is the username? POST to /v1/users/login is failing with 404

### ISSUE THREAD

**Issue by njmurarka** [ripple/gatewayd#527]
Hi. If my domain is foo.com, is my user admin@foo.com?

What is the password?

I tried to login as admin@foo.com, but noticed that the POST to /v1/users/login is failing with a 404. Did I fail to configure something properly?

Thanks

**Comment by stevenzeiler** [comment]
I think you need to set USER_AUTH to `true` in config/config.json

**Comment by cdmcnamara** [comment]
Hi @njmurarka,

Your username should be admin@ + the 'DOMAIN' value in your environment.js file or the value in your config.son file if you choose to override it. The password should be the 'KEY' value in your config.json that you should have setup.

- Conner
