### ISSUE TITLE
"Validation isIn failed: direction", after creating a pending deposit entry

### ISSUE THREAD

**Issue by robby-dermody** [ripple/gatewayd#532]
I'm trying to get a simple gateway working between Counterparty/Bitcoin and Ripple. Upon receiving assets to the bitcoin deposit address for a user (which the gateway controls in its bitcoin hot wallet), I successfully end up creating a pending deposit record in gatewayd with the API (https://ripple.com/build/gatewayd/#record-deposit -- I specify the `external_account_id`, `currency`, `amount` and the bitcoind tx hash as the `data` field).

After this, gatewayd's CPU kicks up, as it repeatedly produces the following error text to the logs:

```
{"data":"6bdf52bbb09ed371b892b6a4d9eadd6103b132e2a0f056b58f0aa94394dcc752","source_amount":null,"destination_amount":null,"amount":10,"id":1,"currency":"XCP","deposit":true,"external_account_id":1,"status":"queued","ripple_transaction_id":null,"createdAt":"2015-01-11T16:54:34.339Z","updatedAt":"2015-01-11T16:54:34.339Z","uid":null,"invoice_id":null,"to_account_id":null,"source_currency":null,"destination_currency":null,"destination_account_id":null,"source_account_id":null,"memos":null,"level":"info","message":"deposit:recorded","timestamp":"2015-01-11T17:55:44.624Z"}
{"direction":["Validation isIn failed: direction"],"level":"error","message":"deposit:failed","timestamp":"2015-01-11T17:55:44.631Z"}
```

The reason looks to be that this code:
https://github.com/ripple/gatewayd/blob/22165c93a91abd7f8fee85759bc00023c38c308c/lib/core/deposit_processor.js#L30

Does not specify a required "direction" parameter. Is this an oversight on ripple dev's part, or is there something I should be doing that I'm not doing (I'm just going from the guide over at https://ripple.com/build/gatewayd)

Thanks for any/all help!

**Comment by robby-dermody** [comment]
Yes, my "attempted fix" seems to work well...

**Comment by cdmcnamara** [comment]
Hi Robby,

The issue is because the 'direction' column in the ripple_transaction does not allow null values and that particular block of code is not populating the field. Feel free to submit a pull request with your fix.

- Conner
