### ISSUE TITLE
Major problem with incoming payment processor

### ISSUE THREAD

**Issue by jaime-ez** [ripple/gatewayd#548]
Hi,
Since today I noticed a change in https://github.com/ripple/ripple-rest#confirm-payment According to the documentation, the output format should be:
![image](https://cloud.githubusercontent.com/assets/4974776/5842849/00e49cf6-a187-11e4-8d5e-0a242d36f9ea.png)

But now it is:
![image](https://cloud.githubusercontent.com/assets/4974776/5842867/261d66f6-a187-11e4-9b36-a23dd59e1c06.png)

As you can see, the hash is now outside the payment object, therefore in lib/core/incoming_payment.js the getPayment function never receives the transaction hash
![image](https://cloud.githubusercontent.com/assets/4974776/5842921/85e1c94c-a187-11e4-96c6-44ded38ee002.png)

This causes that the transaction hash doesn't get updated, you have an incoming payment error and everytime you restart gatewayd you register again all received payment since the last 'manually set' hash.

Could you please tell if I'm reading something wrong here or what, because I haven't found other cause for that error. For now I've changed the code:
![image](https://cloud.githubusercontent.com/assets/4974776/5842996/05d8896a-a188-11e4-8a00-6c7473d569b2.png)

This way I update the hash in the meantime, but if other fields get moved outside the payment object in ripple rest, or anything else..please give a warning!
Best

**Comment by lumberj** [comment]
We are currently running a RC of Ripple-REST at [api.ripple.com](https://api.ripple.com/v1/). We expect to be releasing a new stable version in the next day or so. This API will be changing and the hash of the payment will be on the outside of the payment object. The documentation will be updated as well.

**Comment by cdmcnamara** [comment]
Hey @jaime-ez,

Thanks for catching this. I've gone ahead and committed a fix on develop (https://github.com/ripple/gatewayd/commit/6a7986806020293aedd4dc73397f69ed7b38da9d) and we should have a release pretty soon so this will be in master.

- Conner

**Comment by jaime-ez** [comment]
glad to help
:)
