### ISSUE TITLE
postgres issue : unknown user

### ISSUE THREAD

**Issue by vigen-b** [ripple/gatewayd#554]
Can't run  
<b>sudo -U postgres psql -c "create user gatewayd_user with password 'password'" </b>
I get 
<b>sudo: the `-U' option may only be used with the `-l' option </b>          <-- error
After using -l flag i recieve 
<b>sudo: unknown user: postgres</b>

What command is correct ?

**Comment by achoisy** [comment]
Please use the following command:
sudo <b>-u</b> postgres psql -c "create user gatewayd_user with password 'password'"

**Comment by vigen-b** [comment]
I already finished the setup of the gatewayd but thanks for reply.
